MIDNEAR/MIDNEAR_BACKEND

- .gitignore
- build.gradle
- src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
- src/main/java/com/midnear/midnearshopping/config/SwaggerConfig.java
- src/main/java/com/midnear/midnearshopping/controller/MemberController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/member/LoginDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/member/MemberDto.java
- src/main/java/com/midnear/midnearshopping/domain/vo/member/CustomUserDetails.java
- src/main/java/com/midnear/midnearshopping/domain/vo/member/CustomUserDetailsService.java
- src/main/java/com/midnear/midnearshopping/domain/vo/member/MemberVO.java
- src/main/java/com/midnear/midnearshopping/exception/ApiResponse.java
- src/main/java/com/midnear/midnearshopping/jwt/JwtAuthFilter.java
- src/main/java/com/midnear/midnearshopping/jwt/JwtUtil.java
- src/main/java/com/midnear/midnearshopping/mapper/member/MemberMapper.java
- src/main/java/com/midnear/midnearshopping/service/MemberService.java
- src/main/resources/mapper/MemberMapper.xml
- src/main/resources/project.sql
#3 
-일반 회원가입, jwt발급, 로그인 구현
-전화번호 인증은 곧바로 수행할 예정입니다. 혹시 인증이 필요하신 분이 있을까봐 후다닥 인증 인가만 구현해서 얼른 올립니다
-swagger config 구현: http://localhost:8090/swagger-ui/index.html# 로 접속해서 회원가입, 로그인 후 상단(스크린샷 첨부)에 발급받은 토큰 넣고 실행하시면 됩니다. 필요에 따라 사용해주세요 전 스웨거가 편해서 쓰는겁니다.!
-디자인 상으로는 회원가입 시 주소지 선택이 있는데, 이건 소셜 로그인 이후 구현해서 엮을 예정입니다.
-소셜 로그인이랑 일반 로그인 같이 해보신분.? 일단 전 아니라 좀 무섭네요.. 예제 있으시면 전송 부탁드립니다
> [Feat] norm signup, login#3

- src/main/java/com/midnear/midnearshopping/controller/NoticeController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/notice/NoticeDto.java
- src/main/java/com/midnear/midnearshopping/domain/vo/NoticeVo.java
- src/main/java/com/midnear/midnearshopping/mapper/notice/NoticeMapper.java
- src/main/java/com/midnear/midnearshopping/service/NoticeService.java
- src/main/resources/mapper/NoticeMapper.xml
#4 
공지사항 글 작성, 수정, 삭제, 전체 목록 조회(고정 글과 일반 글 따로 구현됨), 고정 글 설정 및 해제
이미지 구현 안 됨
xml에서 foreach문 사용
https://yaga.tistory.com/688
> [Feat] admin notice#4

- src/main/java/com/midnear/midnearshopping/controller/OAuth2Controller.java
#15
close #15 
프론트엔드에서 인가코드 디코딩 진행하는 불편함을 없애고자 백엔드에서 디코딩 하는 방식으로 변경했습니다.
> [Fix] 인가코드 백엔드에서 디코딩하도록 변경.

- src/main/java/com/midnear/midnearshopping/controller/ConfirmPurchaseController.java
- src/main/java/com/midnear/midnearshopping/controller/OrderController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ConfirmPurchaseDTO.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/OrderDTO.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/OrderParamDTO.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ParamDTO.java
- src/main/java/com/midnear/midnearshopping/mapper/productManagement/ConfirmPurchaseMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/productManagement/OrderProductsMapper.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/ConfirmPurchaseService.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/ConfirmPurchaseServiceImpl.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/OrderProductService.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/OrderProductServiceImpl.java
- src/main/resources/mapper/OrderProductMapper.xml
- src/main/resources/mapper/confirmPurchaseMapper.xml
- src/main/resources/project.sql
#29 
- 구매 확정내역 전체 최신순 필터링
- 구매 확정내역 필터링 검색기능
- 전체 개수 띄우기
디자인 변경이 지속적으로 진행되고 있습니다. 이미 완료하신 파트도
한번 더 체크하고 개발 진행 부탁드립니다.
> Feature/confirmation purchase#29

- src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
- src/main/java/com/midnear/midnearshopping/controller/ProductController.java
- src/main/java/com/midnear/midnearshopping/controller/ProductManagementController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductDetailColorDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductDetailSizeDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductsDetailDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductsListDto.java
- src/main/java/com/midnear/midnearshopping/mapper/products/ProductColorsMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/products/ProductImagesMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/products/ProductsMapper.java
- src/main/java/com/midnear/midnearshopping/service/product/ProductService.java
- src/main/resources/mapper/ProductColorsMapper.xml
- src/main/resources/mapper/ProductImagesMapper.xml
- src/main/resources/mapper/ProductsMapper.xml
#38 
카테고리별, 정렬 포함 상품 가져오는 로직 구현했습니다
정렬은 최신순, 인기순(orderProduct가 많이 참조하는 순) 혹시 몰라서 최저가순 최고 할인순 까지 구현했습니다
상품 구조가 어려워서 좀 오래걸렸듬..
> [Feat] 상품 목록 조회, 상세 조회

- build.gradle
- src/main/java/com/midnear/midnearshopping/controller/CancelProductController.java
- src/main/java/com/midnear/midnearshopping/controller/ConfirmPurchaseController.java
- src/main/java/com/midnear/midnearshopping/controller/OrderShippingController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/CancelProductDTO.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/OptionQuantityDTO.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/OrderReciptDTO.java
- src/main/java/com/midnear/midnearshopping/mapper/productManagement/CancelProductMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/productManagement/OrderShippingMapper.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/CancelProductService.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/CancelProductServiceImpl.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/OrderShippingService.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/OrderShippingServiceImpl.java
- src/main/resources/mapper/CancelProductMapper.xml
- src/main/resources/mapper/OrderShippingMapper.xml
closed#34
-취소내용 전체 , 최신순 조회
-취소내용 필터링 검색
-선택내역 취소 승인처리
-선택내역 취소 거부처리
> [Feat] 취소관리

- src/main/java/com/midnear/midnearshopping/controller/ExchangeController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ExchangeDTO.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ExchangeParamDTO.java
- src/main/java/com/midnear/midnearshopping/mapper/productManagement/ExchangeMapper.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/ExchangeService.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/ExchangeServiceImpl.java
- src/main/resources/mapper/CancelProductMapper.xml
- src/main/resources/mapper/ExchangeMapper.xml
closed#43 
- 교환내역 전체, 최신순 조회
- 교환내역 필터링 검색
- 교환내역 반품처리
- 교환내역 교환 거부처리
- 교환내역 송장번호 , 택배사 입력 처리
> [Feat] 교환관리

- src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
- src/main/java/com/midnear/midnearshopping/controller/NoticeController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/notice/NoticeDto.java
- src/main/java/com/midnear/midnearshopping/mapper/notice/NoticeImagesMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/notice/NoticeMapper.java
- src/main/java/com/midnear/midnearshopping/service/NoticeService.java
- src/main/resources/mapper/NoticeMapper.xml
- src/main/resources/mapper/ProductColorsMapper.xml
closed #4
공지사항 수정 시 이미지 url 반환
공지사항 목록 페이지에서 검색 및 필터링 기능
> [Feat] 공지사항 검색 및 필터링 추가

- src/main/java/com/midnear/midnearshopping/controller/CartController.java
- src/main/java/com/midnear/midnearshopping/controller/UserOrderController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/cart/CartProductDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/order/OrderProductsRequestDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/order/UserOrderDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/order/UserOrderProductsDto.java
- src/main/java/com/midnear/midnearshopping/domain/vo/cart/CartProductsVO.java
- src/main/java/com/midnear/midnearshopping/domain/vo/cart/CartVO.java
- src/main/java/com/midnear/midnearshopping/domain/vo/order/OrderProductsVO.java
- src/main/java/com/midnear/midnearshopping/domain/vo/order/OrdersVO.java
- src/main/java/com/midnear/midnearshopping/mapper/cart/CartMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/cart/CartProductsMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/order/OrderMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/order/UserOrderProductsMapper.java
- src/main/java/com/midnear/midnearshopping/service/cart/CartService.java
- src/main/java/com/midnear/midnearshopping/service/order/OrderNumberGenerator.java
- src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
- src/main/resources/mapper/CartMapper.xml
- src/main/resources/mapper/CartProductsMapper.xml
- src/main/resources/mapper/OrderMapper.xml
- src/main/resources/mapper/OrderProductMapper.xml
- src/main/resources/mapper/UserOrderProductsMapper.xml
#38
주문 DB 생성, 장바구니 생성 추가 삭제 수정
주문 당 사이즈 재고 감소를 주문 디비 만들때 해야할까요? 아니면 주문 확인단계를 관리자 페이지에서 하면.. 그때 수량을 줄여야할까요
> [Feat] 주문 생성, 장바구니

- src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
- src/main/java/com/midnear/midnearshopping/controller/StoreManagementController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/category/CreateCategoryDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/policies_info/PoliciesAndInfoDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/storeImages/StoreImagesDto.java
- src/main/java/com/midnear/midnearshopping/domain/vo/policies_info/PoliciesAndInfoVo.java
- src/main/java/com/midnear/midnearshopping/domain/vo/storeImages/StoreImagesVo.java
- src/main/java/com/midnear/midnearshopping/mapper/Category/CategoriesMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/policies_info/PoliciesAndInfoMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/storeManagement/StoreImagesMapper.java
- src/main/java/com/midnear/midnearshopping/service/StoreManagementService.java
- src/main/resources/mapper/CategoriesMapper.xml
- src/main/resources/mapper/PoliciesAndInfoMapper.xml
- src/main/resources/mapper/StoreImagesMapper.xml
#50 
메인화면 이미지 수정
로고 수정
카테고리 관리
개인정보 처리 방침 관리
이용약관 관리
주소 및 사업자 정보 관리
개인정보 수집 및 이용 목적 관리
> [Feat] 스토어 관리

- src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
- src/main/java/com/midnear/midnearshopping/controller/CouponPointController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/coupon_point/CouponDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/coupon_point/CouponToSelectedUserDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/coupon_point/PointDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/coupon_point/PointToSelectedUserDto.java
- src/main/java/com/midnear/midnearshopping/domain/vo/coupon_point/CouponVo.java
- src/main/java/com/midnear/midnearshopping/domain/vo/coupon_point/PointVo.java
- src/main/java/com/midnear/midnearshopping/domain/vo/coupon_point/ReviewPointVo.java
- src/main/java/com/midnear/midnearshopping/mapper/coupon_point/CouponMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/coupon_point/PointMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/users/UsersMapper.java
- src/main/java/com/midnear/midnearshopping/service/CouponPointService.java
- src/main/resources/mapper/CouponMapper.xml
- src/main/resources/mapper/PointMapper.xml
- src/main/resources/mapper/UsersMapper.xml
#59 
전체 포인트 지급
개별 포인트 지급
사용자 아이디로 검색
전체 쿠폰 지급
개별 쿠폰 지급
리뷰 포인트 설정
리뷰 페이지에서 관리자 승인 시 포인트 지급 남음
> [Feat] 쿠폰/포인트 지급 관리

- src/main/java/com/midnear/midnearshopping/controller/ClaimController.java
- src/main/java/com/midnear/midnearshopping/controller/ReviewController.java
- src/main/java/com/midnear/midnearshopping/controller/UserInquiryController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/Inquiries/UserInquiryListDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/order/UserOrderProductCheckDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/review/ProductReviewDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/review/ReviewListDto.java
- src/main/java/com/midnear/midnearshopping/domain/vo/Inquiries/InquiriesVO.java
- src/main/java/com/midnear/midnearshopping/domain/vo/claim/ClaimListDto.java
- src/main/java/com/midnear/midnearshopping/domain/vo/review/ReviewImagesVO.java
- src/main/java/com/midnear/midnearshopping/mapper/Inquiries/UserInquiryMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/order/UserOrderProductsMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/review/ReviewImagesMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/review/ReviewsMapper.java
- src/main/java/com/midnear/midnearshopping/service/claim/ClaimService.java
- src/main/java/com/midnear/midnearshopping/service/inquirie/UserInquiryService.java
- src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
- src/main/java/com/midnear/midnearshopping/service/review/ReviewsService.java
- src/main/resources/mapper/ReviewImagesMapper.xml
- src/main/resources/mapper/ReviewsMapper.xml
- src/main/resources/mapper/UserCanceledProductMapper.xml
- src/main/resources/mapper/UserInquiryMapper.xml
- src/main/resources/mapper/UserOrderProductsMapper.xml
> [Feat] 문의 클레임 리뷰#38

- src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
- src/main/java/com/midnear/midnearshopping/controller/UserMagazineController.java
- src/main/java/com/midnear/midnearshopping/controller/UserOrderController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/magazines/MagazineResponseDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/magazines/MagazineResponseListDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/order/NonUserOrderDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/order/NonUserOrderInfoRequest.java
- src/main/java/com/midnear/midnearshopping/domain/vo/order/OrdersVO.java
- src/main/java/com/midnear/midnearshopping/mapper/magazines/magazinesMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/order/OrderMapper.java
- src/main/java/com/midnear/midnearshopping/service/magazine/UserMagazineService.java
- src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
- src/main/resources/mapper/MagazinesMapper.xml
- src/main/resources/mapper/OrderMapper.xml
- src/main/resources/mapper/UserCanceledProductMapper.xml
> [Feat] 비회원 주문조회 매거진 조회 #38

- src/main/java/com/midnear/midnearshopping/controller/ProductManagementController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductColorsDto.java
- src/main/java/com/midnear/midnearshopping/mapper/products/ProductsMapper.java
- src/main/java/com/midnear/midnearshopping/service/ProductManagementService.java
- src/main/resources/mapper/ProductColorsMapper.xml
- src/main/resources/mapper/ProductsMapper.xml
#19 
코디 상품 관리 검색 시 연관상품명, 연관상품 등록 일시로 검색 가능
> [Feat] 코디상품 필터링 검색 범위 추가

- src/main/java/com/midnear/midnearshopping/controller/PaymentsController.java
- src/main/java/com/midnear/midnearshopping/controller/productManage/ExchangeController.java
- src/main/java/com/midnear/midnearshopping/controller/productManage/ReturnController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/delivery/DeliveryInfoDTO.java
- src/main/java/com/midnear/midnearshopping/domain/dto/payment/PaymentDbDTO.java
- src/main/java/com/midnear/midnearshopping/domain/dto/payment/SaveAmountRequestDTO.java
- src/main/java/com/midnear/midnearshopping/domain/dto/payment/TossPaymentResponseDTO.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/InvoiceInsertDTO.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ReturnDTO.java
- src/main/java/com/midnear/midnearshopping/exception/PaymentErrorResponse.java
- src/main/java/com/midnear/midnearshopping/mapper/order/PaymentMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/productManagement/ExchangeMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/productManagement/ReturnMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/productManagement/ShippingManagementMapper.java
- src/main/java/com/midnear/midnearshopping/service/disruptive/DisruptiveServiceImpl.java
- src/main/java/com/midnear/midnearshopping/service/order/paymentService.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/DeliveryService.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/DeliveryServiceImpl.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/ExchangeService.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/ExchangeServiceImpl.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/ReturnService.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/ReturnServiceImpl.java
- src/main/resources/mapper/DisruptiveCustomersMapper.xml
- src/main/resources/mapper/ExchangeMapper.xml
- src/main/resources/mapper/PaymentMapper.xml
- src/main/resources/mapper/ReturnMapper.xml
- src/main/resources/mapper/ShippingManagement.xml
- src/main/resources/project.sql
#62 
- 배송정보 실시간 업데이트
- 결제 구현
- 바뀐 컬럼 리펙토링
- 반품, 교환 송장번호 입력 추가
- 상품 수거완료 수동처리
결제 아직 픽스 x
> [Feat] 기타 누락사항

- src/main/java/com/midnear/midnearshopping/domain/dto/claim/ExchangePickupDeliveryDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/review/ReviewListDto.java
- src/main/java/com/midnear/midnearshopping/domain/vo/review/ReviewsVO.java
- src/main/java/com/midnear/midnearshopping/mapper/claim/UserExchangeMapper.java
- src/main/java/com/midnear/midnearshopping/service/claim/ClaimService.java
- src/main/resources/mapper/ReviewsMapper.xml
- src/main/resources/mapper/UserCanceledProductMapper.xml
- src/main/resources/mapper/UserExchangeMapper.xml
#38 
포인트 컬럼추가 및 조회, 생성
교환시 픽업테이블 생성
> [Feat]포인트 추가, 교환시 픽업테이블 생성#38

- src/main/java/com/midnear/midnearshopping/controller/productManage/CancelProductController.java
- src/main/java/com/midnear/midnearshopping/controller/productManage/OrderShippingController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ConfirmPurchaseDTO.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ExchangeDTO.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ExchangeParamDTO.java
- src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/OptionQuantityDTO.java
- src/main/resources/mapper/ExchangeMapper.xml
- src/main/resources/mapper/OrderShippingMapper.xml
> [Chore] 자잘한 수정

- src/main/java/com/midnear/midnearshopping/config/CorsConfig.java
- src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
- src/main/java/com/midnear/midnearshopping/controller/DeliveryController.java
- src/main/java/com/midnear/midnearshopping/controller/UserMagazineController.java
- src/main/java/com/midnear/midnearshopping/controller/UserOrderController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/magazines/MagazineResponseDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/order/OrderDetailsDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/order/UserOrderProductCheckDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/payment/PaymentInfoDto.java
- src/main/java/com/midnear/midnearshopping/mapper/delivery/DeliveryInfoMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/magazines/magazinesMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/order/OrderMapper.java
- src/main/java/com/midnear/midnearshopping/service/delivery/DeliveryService.java
- src/main/java/com/midnear/midnearshopping/service/magazine/UserMagazineService.java
- src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
- src/main/resources/mapper/DeliveryInfoMapper.xml
- src/main/resources/mapper/MagazinesMapper.xml
- src/main/resources/mapper/OrderMapper.xml
- src/main/resources/mapper/ReviewsMapper.xml
> [Fix] Cors,매거진 픽스#38

- src/main/java/com/midnear/midnearshopping/controller/CouponPointController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/coupon_point/PointDto.java
- src/main/java/com/midnear/midnearshopping/domain/vo/coupon_point/PointVo.java
- src/main/java/com/midnear/midnearshopping/mapper/coupon_point/PointMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/coupon_point/ReviewPointMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/review/ReviewImagesMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/review/ReviewsMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/users/UsersMapper.java
- src/main/java/com/midnear/midnearshopping/service/CouponPointService.java
- src/main/resources/mapper/PointMapper.xml
- src/main/resources/mapper/ReviewImagesMapper.xml
- src/main/resources/mapper/ReviewPointMapper.xml
- src/main/resources/mapper/ReviewsMapper.xml
- src/main/resources/mapper/UsersMapper.xml
close #59 
관리자가 리뷰 승인 시 사용자에게 포인트 지급 (텍스트 리뷰, 포인트 리뷰)
> [Feat] 리뷰 포인트 적립

- src/main/java/com/midnear/midnearshopping/controller/NoticeController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/notice/PopupDto.java
- src/main/java/com/midnear/midnearshopping/mapper/notice/NoticeImagesMapper.java
- src/main/java/com/midnear/midnearshopping/service/notice/NoticeService.java
- src/main/resources/mapper/NoticeImagesMapper.xml
> [Feat] 메인 화면 팝업 이미지

- src/main/java/com/midnear/midnearshopping/config/CorsConfig.java
- src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
- src/main/java/com/midnear/midnearshopping/controller/ReviewController.java
- src/main/java/com/midnear/midnearshopping/controller/UserCouponPointController.java
- src/main/java/com/midnear/midnearshopping/controller/UserMagazineController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/coupon_point/UserPointDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/review/CommentDto.java
- src/main/java/com/midnear/midnearshopping/mapper/magazines/magazinesMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/review/ReviewsMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/users/UsersMapper.java
- src/main/java/com/midnear/midnearshopping/service/CouponPointService.java
- src/main/java/com/midnear/midnearshopping/service/magazine/UserMagazineService.java
- src/main/java/com/midnear/midnearshopping/service/review/ReviewsService.java
- src/main/resources/mapper/MagazinesMapper.xml
- src/main/resources/mapper/PointMapper.xml
- src/main/resources/mapper/UserCouponMapper.xml
> [Fix] 유저쪽 버그 픽스, 리팩토링#73

- src/main/java/com/midnear/midnearshopping/config/CorsConfig.java
- src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
- src/main/java/com/midnear/midnearshopping/controller/UserOrderController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/payment/PaymentInfoDto.java
- src/main/java/com/midnear/midnearshopping/mapper/delivery/DeliveryAddressMapper.java
- src/main/java/com/midnear/midnearshopping/service/order/OrderNumberGenerator.java
- src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
- src/main/java/com/midnear/midnearshopping/service/order/PostalCodeChecker.java
- src/main/resources/mapper/DeliveryAddressMapper.xml
- src/main/resources/mapper/OrderMapper.xml
- src/main/resources/mapper/UsersMapper.xml
> [Fix] userbugfix#73

- src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
- src/main/java/com/midnear/midnearshopping/controller/ProductController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/products/CoordinateProductDto.java
- src/main/java/com/midnear/midnearshopping/mapper/products/ProductsMapper.java
- src/main/java/com/midnear/midnearshopping/service/claim/ClaimService.java
- src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
- src/main/java/com/midnear/midnearshopping/service/product/ProductService.java
- src/main/resources/mapper/CartProductsMapper.xml
- src/main/resources/mapper/ProductsMapper.xml
- src/main/resources/mapper/UserOrderProductsMapper.xml
Related to: #38#38
#38
#73
장바구니, 교환취소환불 리팩토링
> [Refactor] 장바구니, 교환취소환불 리팩토링#73

- src/main/java/com/midnear/midnearshopping/domain/dto/delivery/DeliveryAddrDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/review/ReviewRequestDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/users/UsersDto.java
- src/main/java/com/midnear/midnearshopping/domain/vo/cart/CartVO.java
- src/main/java/com/midnear/midnearshopping/domain/vo/coupon_point/UserCouponVO.java
- src/main/java/com/midnear/midnearshopping/domain/vo/delivery/DeliveryAddressVO.java
- src/main/java/com/midnear/midnearshopping/domain/vo/order/OrdersVO.java
- src/main/java/com/midnear/midnearshopping/domain/vo/review/ReviewsVO.java
- src/main/java/com/midnear/midnearshopping/domain/vo/users/UsersVO.java
- src/main/java/com/midnear/midnearshopping/mapper/cart/CartMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/coupon_point/PointMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/coupon_point/UserCouponMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/delivery/DeliveryAddressMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/order/OrderMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/users/UsersMapper.java
- src/main/java/com/midnear/midnearshopping/service/CouponPointService.java
- src/main/java/com/midnear/midnearshopping/service/cart/CartService.java
- src/main/java/com/midnear/midnearshopping/service/claim/ClaimService.java
- src/main/java/com/midnear/midnearshopping/service/delivery/DeliveryService.java
- src/main/java/com/midnear/midnearshopping/service/inquirie/UserInquiryService.java
- src/main/java/com/midnear/midnearshopping/service/oauth/OAuthService.java
- src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
- src/main/java/com/midnear/midnearshopping/service/review/ReviewsService.java
> [Refactor] Oauth Refactor#73

- src/main/java/com/midnear/midnearshopping/controller/ProductController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductListInfoDto.java
- src/main/java/com/midnear/midnearshopping/mapper/products/ProductsMapper.java
- src/main/java/com/midnear/midnearshopping/service/product/ProductService.java
- src/main/resources/mapper/ProductsMapper.xml
#38 
연동중 프엔 요청으로 전체상품 수와 페이지크기 리턴api생성
> [Feat] FE요청: 전체상품 수와 페이지크기 리턴#73

- src/main/java/com/midnear/midnearshopping/controller/StoreManagementController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/Statistics/StatisticsDto.java
- src/main/java/com/midnear/midnearshopping/mapper/storeManagement/StatisticsMapper.java
- src/main/java/com/midnear/midnearshopping/service/StoreManagementService.java
- src/main/resources/mapper/StatisticsMapper.xml
> [Fix] 매출 타입 수정

- src/main/java/com/midnear/midnearshopping/controller/CouponPointController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductsDto.java
- src/main/java/com/midnear/midnearshopping/domain/vo/products/ProductsVo.java
> [Fix]  상품 등록 시 날짜 오류 수정

- src/main/java/com/midnear/midnearshopping/config/CorsConfig.java
> [Fix] Cors에 프엔 배포 추가

- src/main/java/com/midnear/midnearshopping/config/CorsConfig.java
관련있는 이슈 번호(#000)을 적어주세요.
#38 
오타수정
> [Fix] Cors에 프엔 배포 추가 수정:

- src/main/java/com/midnear/midnearshopping/controller/ProductController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductListInfoDto.java
- src/main/java/com/midnear/midnearshopping/mapper/products/ProductsMapper.java
- src/main/java/com/midnear/midnearshopping/service/product/ProductService.java
- src/main/resources/mapper/ProductsMapper.xml
> [Feat] fe요청 처리#73

- src/main/java/com/midnear/midnearshopping/controller/SmsController.java
#73 
문자인증 기능만 https에서 
Error parsing HTTP request header발생... 고치는중이라 몇번 다시 올릴수도 있어요
> [Fix]Error parsing HTTP request header해결 #73

- src/main/java/com/midnear/midnearshopping/service/product/ProductService.java
> [Fix]페이징 바보짓 해결 #73

- src/main/java/com/midnear/midnearshopping/controller/StoreManagementController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/policies_info/PoliciesAndInfoDto.java
- src/main/java/com/midnear/midnearshopping/mapper/policies_info/PoliciesAndInfoMapper.java
- src/main/java/com/midnear/midnearshopping/mapper/storeManagement/StoreImagesMapper.java
- src/main/java/com/midnear/midnearshopping/service/StoreManagementService.java
- src/main/resources/mapper/PoliciesAndInfoMapper.xml
- src/main/resources/mapper/StoreImagesMapper.xml
#50 
DB에서 해당 데이터 찾을 때 vo.getImageUrl() 대신 필요한 url만 반환하도록 하여 해결
이용약관 리팩토링 dto빼고 String만 받음
> [Fix] 메인, 로고 이미지 업로드 시 nullPoint 에러, 이용약관 리팩토링

- src/main/java/com/midnear/midnearshopping/mapper/ShippingReturns/ShippingReturnsMapper.java
- src/main/java/com/midnear/midnearshopping/service/ProductManagementService.java
- src/main/resources/mapper/ShippingReturnsMapper.xml
#19 
정보 등록 시 이전 정보 지우고 새로 생성하도록 로직 변경
> [Fix] shipping&returns 리팩토링

- src/main/java/com/midnear/midnearshopping/domain/dto/coordinate/ColorDto.java
- src/main/java/com/midnear/midnearshopping/domain/dto/coordinate/MainProductDto.java
- src/main/java/com/midnear/midnearshopping/service/ProductManagementService.java
#19 
연관 상품 list가 잘못 들어가있어서 수정했습니다
> [Fix] 코디 상품 dto 수정

- src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
- src/main/java/com/midnear/midnearshopping/controller/UserOrderController.java
- src/main/java/com/midnear/midnearshopping/mapper/order/OrderMapper.java
- src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
- src/main/resources/mapper/OrderMapper.xml
#73 #38 
배송비 컬럼 추가에 따라서 무료배송인지 확인하는 api추가했습니다~~
> [Feat]무료배송인지 조회#73

- src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductsListDto.java
- src/main/resources/mapper/ProductsMapper.xml
#73 
상품리스트에 판매상태, 할인기간 포함/이미지 제대로 나오게 수정
> [Feat]상품리스트에 판매상태, 할인기간 포함/이미지 제대로 나오게 수정

- src/main/java/com/midnear/midnearshopping/domain/vo/products/ProductsVo.java
#19 
할인 기간 안 받으면 null로 처리되도록 수정했습니다.
> [Fix] 상품 등록 시 할인 기간 null 가능

- src/main/java/com/midnear/midnearshopping/service/product/ProductService.java
- src/main/java/com/midnear/midnearshopping/service/review/ReviewsService.java
> [Feat] FE요청: 페이지 사이즈 4로 수정 #73

- src/main/java/com/midnear/midnearshopping/mapper/products/ProductColorsMapper.java
- src/main/java/com/midnear/midnearshopping/service/ProductManagementService.java
- src/main/resources/mapper/ProductColorsMapper.xml
- src/main/resources/mapper/ProductsMapper.xml
#19 
관리자가 상품 관리에서 한 상품의 모든 컬러를 삭제하는 경우 상위 정보(products 테이블)인 공통 정보도 삭제하도록 수정
상품 검색 조회 파라미터 순서가 잘못 되어있었음. 수정했습니다.
> [Fix] 상품 삭제, 상품 검색 수정

- src/main/java/com/midnear/midnearshopping/service/UsersService.java
- src/main/java/com/midnear/midnearshopping/service/inquirie/UserInquiryService.java
- src/main/java/com/midnear/midnearshopping/service/review/ReviewsService.java
- src/main/resources/mapper/CartMapper.xml
- src/main/resources/mapper/UsersMapper.xml
#38 #73
리뷰 권한 체크 수정, 페이지 사이즈 및 장바구니 회원가입시 생기도록 수정
> [Fix] 리뷰 권한 체크 수정, 페이지 사이즈 및 장바구니 회원가입시 생기도록 수정

- src/main/java/com/midnear/midnearshopping/domain/dto/cart/CartProductDto.java
- src/main/resources/mapper/CartProductsMapper.xml
> [Fix] 장바구니 상품 수정#73

- src/main/java/com/midnear/midnearshopping/controller/DeliveryController.java
- src/main/java/com/midnear/midnearshopping/mapper/delivery/DeliveryAddressMapper.java
- src/main/java/com/midnear/midnearshopping/service/delivery/DeliveryService.java
- src/main/resources/mapper/DeliveryAddressMapper.xml
> [Fix] 배송지 수정

- src/main/java/com/midnear/midnearshopping/controller/StoreManagementController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/policies_info/PolicyDto.java
#50
String 객체만 받는 것이 안 돼서 dto로 수정했습니다.
> [Fix] String Dto로 감싸기

- src/main/java/com/midnear/midnearshopping/service/delivery/DeliveryService.java
#38 #32 #73 
배송지 새로 등록시 기본 배송지로 설정할 경우 기존 기본 배송지 0으로 바뀌게 바꿈
> [Fix]배송지 수정 #73

- src/main/java/com/midnear/midnearshopping/service/delivery/DeliveryService.java
> [Fix]배송지 수정

- src/main/java/com/midnear/midnearshopping/service/delivery/DeliveryService.java
> [Fix]배송지 수정 진짜 최종 #73

- src/main/java/com/midnear/midnearshopping/MidnearShoppingApplication.java
- src/main/java/com/midnear/midnearshopping/controller/productManage/ShippingManageController.java
- src/main/java/com/midnear/midnearshopping/mapper/productManagement/ShippingManagementMapper.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/ShippingManageService.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/ShippingManageServiceImpl.java
- src/main/resources/mapper/DisruptiveCustomersMapper.xml
- src/main/resources/mapper/MagazinesMapper.xml
- src/main/resources/mapper/ShippingManagement.xml
> [Feat] 배송비 띄우기

- src/main/java/com/midnear/midnearshopping/controller/DisruptiveController.java
- src/main/java/com/midnear/midnearshopping/controller/InquirieController.java
- src/main/java/com/midnear/midnearshopping/controller/MagazinesController.java
- src/main/java/com/midnear/midnearshopping/controller/productManage/CancelProductController.java
- src/main/java/com/midnear/midnearshopping/controller/productManage/ConfirmPurchaseController.java
- src/main/java/com/midnear/midnearshopping/controller/productManage/ExchangeController.java
- src/main/java/com/midnear/midnearshopping/controller/productManage/OrderController.java
- src/main/java/com/midnear/midnearshopping/controller/productManage/OrderShippingController.java
- src/main/java/com/midnear/midnearshopping/controller/productManage/ReturnController.java
- src/main/java/com/midnear/midnearshopping/controller/productManage/ShippingManageController.java
- src/main/java/com/midnear/midnearshopping/domain/dto/delivery/FreeBasicConditionDTO.java
- src/main/java/com/midnear/midnearshopping/mapper/productManagement/ShippingManagementMapper.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/ShippingManageService.java
- src/main/java/com/midnear/midnearshopping/service/productManagement/ShippingManageServiceImpl.java
- src/main/resources/mapper/ShippingManagement.xml
- 기본배송가격, 무료배송 가격 띄우기
- 관리자페이지 보안처리 완료
> [Feat] 배송api 추가 및 보안처리

- src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
- src/main/java/com/midnear/midnearshopping/controller/productManage/ShippingManageController.java
배송비 가져오는부분 사용자 파트에서 풀어둠
Related to: #58
배송파트 관리자 보안처리 뺌
> [Chore] 배송부분 엔드포인트 추가

- src/main/java/com/midnear/midnearshopping/mapper/review/ReviewImagesMapper.java
- src/main/java/com/midnear/midnearshopping/service/review/ReviewsService.java
- src/main/resources/mapper/ReviewImagesMapper.xml
- src/main/resources/mapper/ReviewsMapper.xml
> [Fix]리뷰 페이징 오류 해결 #73

- src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
> [Fix]푸터 로그인 없이 가져오게 수정

- src/main/java/com/midnear/midnearshopping/controller/ReviewController.java
- src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
- src/main/resources/mapper/OrderMapper.xml
> [Fix]주문정보 페이징 수정#73
